# Image Python officielle
FROM python:3.11-slim

# Définir le dossier de travail
WORKDIR /app

# Copier le fichier requirements.txt depuis la racine du projet
COPY requirements.txt .

# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Copier le contenu du dossier backend dans /app
COPY ./fastprom /app

# Exposer le port FastAPI
EXPOSE 8000

# Lancer le serveur FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]


#docker build -t oai-backend -f dockerfile .
#docker run -p 8000:8000 oai-backend