FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y curl gnupg2 lsb-release tshark && \
    apt-get install -y python3 python3-pip && \
    apt-get install -y libsctp1 lksctp-tools && \
    apt-get install -y libyaml-cpp0.8 && \
    apt-get install -y git && \
    apt-get install -y libusb-1.0-0 && \
    apt-get install -y cmake && \
    apt-get install -y build-essential && \
    apt-get install -y libboost-all-dev && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list && \
    apt-get update && \
    apt-get install -y docker-ce-cli && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get remove -y python3-yaml || true && \
    apt-get install -y cmake build-essential

RUN apt-get update && \
    apt-get install -y python3-mako && \
    apt-get install -y python3-requests && \
    apt-get install -y python3-numpy && \
    apt-get install -y python3-ruamel.yaml && \
    apt-get install -y udev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y usbutils

RUN apt-get install -y libusb-1.0-0-dev

RUN git clone --recurse-submodules https://github.com/EttusResearch/uhd.git /opt/uhd && \
    cd /opt/uhd && \
    git checkout v4.7.0.0 && \
    git submodule update --init --recursive && \
    mkdir -p /opt/uhd/host/build && \
    cd /opt/uhd/host/build && \
    cmake .. && \
    make -j$(nproc) && \
    make install && \
    ldconfig && \
    uhd_images_downloader

WORKDIR /app

COPY requirements.txt .

RUN pip3 install --no-cache-dir --break-system-packages -r requirements.txt

COPY . /app

CMD ["uvicorn", "backend.api:app", "--host", "0.0.0.0", "--port", "8000"]
